from datetime import datetime
from typing import Literal

from pydantic import BaseModel

AuditActorType = Literal["user", "system", "agent"]
AuditAction = Literal[
    "requirement_created",
    "requirement_analyzed",
    "task_decomposition_created",
    "dev_task_updated",
    "dev_task_assigned",
    "subtask_updated",
    "subtask_assigned",
    "approval_requested",
    "approval_approved",
    "approval_rejected",
    "approval_needs_revision",
    "change_requested",
    "code_repository_created",
    "code_repository_updated",
    "repo_safety_profile_updated",
    "requirement_generation_created",
    "epic_created",
    "epic_updated",
    "check_definition_created",
    "check_definition_updated",
    "check_run_recorded",
    "tool_runner_definition_created",
    "tool_runner_definition_updated",
    "tool_run_recorded",
    "openhands_package_prepared",
    "openhands_result_recorded",
    "openhands_execution_requested",
    "openhands_execution_started",
    "openhands_execution_completed",
    "openhands_execution_failed",
    "openhands_execution_timed_out",
    "openhands_execution_blocked",
    "git_inspection_completed",
    "workspace_branch_created",
    "workspace_branch_inspected",
    "workspace_commit_prepared",
    "workspace_commit_created",
    "workspace_commit_failed",
    "git_operation_blocked",
    "openhands_workspace_synced",
    "integration_run_requested",
    "integration_run_completed",
    "integration_run_conflict",
    "integration_run_failed",
    "aider_package_prepared",
    "aider_result_recorded",
    "aider_workspace_synced",
    "aider_execution_requested",
    "aider_execution_started",
    "aider_execution_completed",
    "aider_execution_failed",
    "aider_execution_timed_out",
    "aider_execution_blocked",
    "github_pr_creation_requested",
    "github_branch_pushed",
    "github_pr_created",
    "github_pr_creation_failed",
    "github_pr_creation_blocked",
    "review_feedback_created",
    "review_feedback_imported",
    "review_feedback_updated",
    "review_feedback_rejected",
    "review_feedback_deferred",
    "review_feedback_resolved",
    "revision_work_item_planned",
    "pr_review_remediation_planned",
    "runner_route_previewed",
    "revision_work_item_updated",
    "pr_draft_prepared",
    "pr_draft_updated",
    "pr_draft_approved",
    "pr_review_requested",
    "pr_review_recorded",
    "pr_review_completed",
    "ci_event_recorded",
    "ci_analysis_requested",
    "ci_analysis_completed",
    "ci_analysis_failed",
    "incident_recorded",
    "incident_updated",
    "incident_analysis_requested",
    "incident_analysis_completed",
    "incident_analysis_failed",
    "remediation_work_item_prepared",
    "memory_learning_requested",
    "memory_learning_completed",
    "memory_learning_failed",
    "memory_candidate_created",
    "memory_candidate_approved",
    "memory_candidate_rejected",
    "project_memory_learned",
    "workspace_created",
    "workspace_registered",
    "workspace_inspected",
    "workspace_archived",
    "workspace_invalid",
    "command_definition_created",
    "command_definition_updated",
    "command_run_requested",
    "command_run_blocked",
    "command_run_completed",
    "command_run_failed",
    "command_run_timed_out",
    "check_execution_requested",
    "check_execution_completed",
    "check_execution_failed",
    "check_execution_blocked",
    "research_brief_created",
    "research_brief_generated",
    "research_brief_updated",
    "research_brief_archived",
    "research_source_created",
    "research_source_updated",
    "research_source_deleted",
    "architecture_review_created",
    "architecture_review_generated",
    "architecture_review_updated",
    "architecture_review_archived",
    "improvement_proposal_created",
    "improvement_proposal_updated",
    "improvement_proposal_approved",
    "improvement_proposal_rejected",
    "improvement_proposal_deferred",
    "improvement_proposal_implemented",
    "improvement_proposal_archived",
    "architecture_decision_created",
    "architecture_decision_updated",
    "architecture_decision_accepted",
    "architecture_decision_rejected",
    "architecture_decision_deprecated",
    "architecture_decision_superseded",
    "experiment_plan_created",
    "experiment_plan_updated",
    "experiment_plan_approved",
    "experiment_plan_rejected",
    "experiment_run_created",
    "experiment_run_updated",
    "experiment_run_completed",
    "project_retrospective_created",
    "project_retrospective_generated",
    "project_retrospective_updated",
    "project_retrospective_archived",
    "project_template_created",
    "project_template_updated",
    "project_template_archived",
    "project_templates_seeded",
    "workflow_template_created",
    "workflow_template_updated",
    "workflow_template_archived",
    "workflow_templates_seeded",
    "project_pack_created",
    "project_pack_updated",
    "project_pack_archived",
    "project_packs_seeded",
    "work_safe_policy_created",
    "work_safe_policy_updated",
    "work_safe_policy_archived",
    "work_safe_action_checked",
    "audit_export_requested",
    "audit_export_updated",
    "backup_export_requested",
    "backup_export_completed",
    "backup_export_failed",
    "backup_import_dry_run_completed",
    "backup_import_completed",
    "backup_import_failed",
]


class AuditEvent(BaseModel):
    id: str
    project_id: str | None = None
    actor_type: AuditActorType
    actor_id: str
    action: AuditAction
    target_type: str
    target_id: str
    details: dict = {}
    created_at: datetime
